export const SchoolMappings: Record<string, string> = {
  OHST: 'Ohio State',
  MICH: 'Michigan',
  TEX: 'Texas',
  GTECH: 'Georgia Tech',
  UMASS: 'UMass',
  HOU: 'Houston',
  OHIO: 'Ohio University',
  KAN: 'Kansas',
  OKLA: 'Oklahoma',
  ECU: 'East Carolina',
  MIST: 'Michigan State',
  ILL: 'Illinois',
  IND: 'Indiana',
  NEB: 'Nebraska',
  CAL: 'California',
  WSU: 'Washington State',
  NWEST: 'Northwestern',
  ARIZ: 'Arizona',
  PITT: 'Pittsburgh',
  WASH: 'Washington',
  BC: 'Boston College',
  PUR: 'Purdue',
  UGA: 'Georgia',
  VTECH: 'Virginia Tech',
  STAN: 'Stanford',
  ARK: 'Arkansas',
  OKST: 'Oklahoma State',
  MIZZ: 'Missouri',
  ORST: 'Oregon State',
  ND: 'Notre Dame',
  TEM: 'Temple',
  UVA: 'Virginia',
  SCAR: 'South Carolina',
  CLEM: 'Clemson',
  KY: 'Kentucky',
  AUB: 'Auburn',
  VAN: 'Vanderbilt',
  UF: 'Florida',
  AZST: 'Arizona State',
  IAST: 'Iowa State',
  HAW: 'Hawaii',
  PSU: 'Penn State',
  WVU: 'West Virginia',
  TTECH: 'Texas Tech',
  NCST: 'NC State',
  WIS: 'Wisconsin',
  JM: 'James Madison',
  LOU: 'Louisville',
  RUTG: 'Rutgers',
  MSST: 'Mississippi State',
  MISS: 'Ole Miss',
  CIN: 'Cincinnati',
  MIA: 'Miami',
  MRSHL: 'Marshall',
  MARY: 'Maryland',
  IDAHO: 'Idaho',
  BOISE: 'Boise State',
  TAMU: 'Texas A&M',
  CSU: 'Colorado State',
  KSST: 'Kansas State',
  BAMA: 'Alabama',
  BAY: 'Baylor',
  ORE: 'Oregon',
  TENN: 'Tennesse',
  EWU: 'Eastern Washington University',
  HARV: 'Harvard',
};